"""Add user.patronomic

Revision ID: 8adfbd478853
Revises: 3e8b58a5465f
Create Date: 2025-02-23 14:20:34.656608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adfbd478853'
down_revision: Union[str, None] = 'efa7dd68009d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronomic', sa.String(200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronomic')

    # ### end Alembic commands ###
