"""Delete column user.has_sale

Revision ID: 9506bdfac918
Revises: efa7dd68009d
Create Date: 2025-02-23 14:12:51.464048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9506bdfac918'
down_revision: Union[str, None] = 'efa7dd68009d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_sale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
