name: Lint and Test

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Укажите версию Python, которую использует ваш проект

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy black isort

      - name: Run flake8
        run: |
          flake8 module_29_testing/hw/testing_homework/main

      - name: Run mypy
        run: |
          mypy module_29_testing/hw/testing_homework/main

      - name: Run black
        run: |
          black --diff --check module_29_testing/hw/testing_homework/main

      - name: Run isort
        run: |
          isort --check-only module_29_testing/hw/testing_homework/main          
          

      - name: Run tests
        run: |
          pytest module_29_testing/hw/testing_homework/tests
      
