version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my_network

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=skillbox_db
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./config/postgresql/postgresql.conf:/etc/postgresql.conf
      - ./logs/postgresql:/var/log/postgresql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge